# followed_authors.yaml
followed_authors:
  - name:Wang Jianguo
    orcid: "0000-0020-4172-6857"
    names:
      - Wang Jianguo
      - A. Persily

  - name: Da Yan
    orcid: "0000-0003-2399-723X"
    names:
      - Da Yan

  - name: Dirk Müller
    orcid: "0000-0002-6106-6607"
    names:
      - Dirk Müller
